//tflite all in one
// #pragma once

#include "tensorflow/lite/kernels/conv.cc"

#include "tensorflow/lite/kernels/activations.cc"
#include "tensorflow/lite/kernels/add.cc"
#include "tensorflow/lite/kernels/arg_min_max.cc"
#include "tensorflow/lite/kernels/audio_spectrogram.cc"
#include "tensorflow/lite/kernels/basic_rnn.cc"
#include "tensorflow/lite/kernels/batch_to_space_nd.cc"
#include "tensorflow/lite/kernels/bidirectional_sequence_lstm.cc"
#include "tensorflow/lite/kernels/bidirectional_sequence_rnn.cc"
#include "tensorflow/lite/kernels/cast.cc"
#include "tensorflow/lite/kernels/comparisons.cc"
#include "tensorflow/lite/kernels/concatenation.cc"
#include "tensorflow/lite/kernels/depthwise_conv.cc"
#include "tensorflow/lite/kernels/dequantize.cc"
#include "tensorflow/lite/kernels/detection_postprocess.cc"
#include "tensorflow/lite/kernels/div.cc"
#include "tensorflow/lite/kernels/elementwise.cc"
#include "tensorflow/lite/kernels/embedding_lookup.cc"
#include "tensorflow/lite/kernels/embedding_lookup_sparse.cc"
#include "tensorflow/lite/kernels/exp.cc"
#include "tensorflow/lite/kernels/expand_dims.cc"
#include "tensorflow/lite/kernels/fake_quant.cc"
#include "tensorflow/lite/kernels/fill.cc"
#include "tensorflow/lite/kernels/floor.cc"
#include "tensorflow/lite/kernels/floor_div.cc"
#include "tensorflow/lite/kernels/floor_mod.cc"
#include "tensorflow/lite/kernels/fully_connected.cc"
#include "tensorflow/lite/kernels/gather.cc"
#include "tensorflow/lite/kernels/gemm_support.cc"
#include "tensorflow/lite/kernels/hashtable_lookup.cc"
#include "tensorflow/lite/kernels/kernel_util.cc"
#include "tensorflow/lite/kernels/l2norm.cc"
#include "tensorflow/lite/kernels/layer_norm_lstm.cc"
#include "tensorflow/lite/kernels/local_response_norm.cc"
#include "tensorflow/lite/kernels/logical.cc"
#include "tensorflow/lite/kernels/lsh_projection.cc"
#include "tensorflow/lite/kernels/lstm.cc"
#include "tensorflow/lite/kernels/lstm_eval.cc"
#include "tensorflow/lite/kernels/maximum_minimum.cc"
#include "tensorflow/lite/kernels/mfcc.cc"
#include "tensorflow/lite/kernels/mirror_pad.cc"
#include "tensorflow/lite/kernels/mul.cc"
#include "tensorflow/lite/kernels/neg.cc"
#include "tensorflow/lite/kernels/one_hot.cc"
#include "tensorflow/lite/kernels/pack.cc"
#include "tensorflow/lite/kernels/pad.cc"
#include "tensorflow/lite/kernels/pooling.cc"
#include "tensorflow/lite/kernels/pow.cc"
#include "tensorflow/lite/kernels/range.cc"
#include "tensorflow/lite/kernels/reduce.cc"
#include "tensorflow/lite/kernels/register.cc"
#include "tensorflow/lite/kernels/relu1.cc"
#include "tensorflow/lite/kernels/reshape.cc"
#include "tensorflow/lite/kernels/resize_bilinear.cc"
#include "tensorflow/lite/kernels/resize_nearest_neighbor.cc"
#include "tensorflow/lite/kernels/select.cc"
#include "tensorflow/lite/kernels/shape.cc"
#include "tensorflow/lite/kernels/skip_gram.cc"
#include "tensorflow/lite/kernels/slice.cc"
#include "tensorflow/lite/kernels/space_to_batch_nd.cc"
#include "tensorflow/lite/kernels/space_to_depth.cc"
#include "tensorflow/lite/kernels/sparse_output_fully_connected.cc"
#include "tensorflow/lite/kernels/sparse_to_dense.cc"
#include "tensorflow/lite/kernels/split.cc"
#include "tensorflow/lite/kernels/split_v.cc"
#include "tensorflow/lite/kernels/squared_difference.cc"
#include "tensorflow/lite/kernels/squeeze.cc"
#include "tensorflow/lite/kernels/strided_slice.cc"
#include "tensorflow/lite/kernels/sub.cc"
#include "tensorflow/lite/kernels/svdf.cc"
#include "tensorflow/lite/kernels/tile.cc"
#include "tensorflow/lite/kernels/topk_v2.cc"
#include "tensorflow/lite/kernels/transpose.cc"
#include "tensorflow/lite/kernels/transpose_conv.cc"
#include "tensorflow/lite/kernels/unidirectional_sequence_lstm.cc"
#include "tensorflow/lite/kernels/unidirectional_sequence_rnn.cc"
#include "tensorflow/lite/kernels/unpack.cc"
#include "tensorflow/lite/kernels/zeros_like.cc"

#include "tensorflow/lite/kernels/internal/kernel_utils.cc"
#include "tensorflow/lite/kernels/internal/mfcc.cc"
#include "tensorflow/lite/kernels/internal/mfcc_dct.cc"
#include "tensorflow/lite/kernels/internal/mfcc_mel_filterbank.cc"
#include "tensorflow/lite/kernels/internal/quantization_util.cc"
#include "tensorflow/lite/kernels/internal/spectrogram.cc"
#include "tensorflow/lite/kernels/internal/tensor_utils.cc"

#include "tensorflow/lite/kernels/internal/reference/portable_tensor_utils.cc"
#include "tensorflow/lite/kernels/internal/optimized/neon_tensor_utils.cc"

#include "tensorflow/lite/allocation.cc"
#include "tensorflow/lite/arena_planner.cc"
#include "tensorflow/lite/graph_info.cc"
#include "tensorflow/lite/interpreter.cc"
#include "tensorflow/lite/mmap_allocation.cc"
//#include "tensorflow/lite/mmap_allocation_disabled.cc"
#include "tensorflow/lite/model.cc"
#include "tensorflow/lite/mutable_op_resolver.cc"
#include "tensorflow/lite/nnapi_delegate.cc"
//#include "tensorflow/lite/nnapi_delegate_disabled.cc"
#include "tensorflow/lite/optional_debug_tools.cc"
#include "tensorflow/lite/simple_memory_arena.cc"
#include "tensorflow/lite/stderr_reporter.cc"
#include "tensorflow/lite/string_util.cc"
#include "tensorflow/lite/util.cc"

#include "tensorflow/lite/core/subgraph.cc"
#include "tensorflow/lite/core/api/error_reporter.cc"
#include "tensorflow/lite/core/api/flatbuffer_conversions.cc"
#include "tensorflow/lite/core/api/op_resolver.cc"

#include "tensorflow/lite/c/c_api_internal.c"

extern "C" {
#include "fft4g.c"
}

#include "tensorflow/lite/kernels/eigen_support.cc"

#include "farmhash.cc"
